### ISSUE TITLE
create-react-app: Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird     at Array.map (native)

### ISSUE THREAD

**Issue by axlider** [react-toolbox/react-toolbox-themr#12]
I followed instructions from documentation two times with fresh workspaces, but still getting the same error. Please notice i use windows 7, as i have seen there have been issues on windows systems.
# Error:

Failed to compile.
Error in ./react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird
   at Array.map (native)
   ./react-toolbox/lib/button/theme.css 4:14-120 13:2-17:4 14:20-126

Error in ./~/react-toolbox/lib/radio/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".radioChecked", ".radioChecked" is weird
    at Array.map (native)
   ./react-toolbox/lib/radio/theme.css 4:14-120 13:2-17:4 14:20-126

Error in ./~/react-toolbox/lib/switch/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".disabled", ".disabled" is weird
    at Array.map (native)
   ./react-toolbox/lib/switch/theme.css 4:14-120 13:2-17:4 14:20-126

# Project setup:

- create-react-app MyApp
- yarn add react-toolbox@2.0.0-beta.6 react-toolbox-themr
- yarn add redux
- yarn add react-redux
- yarn add redux-thunk
- yarn add react-style-proptype (missing dependency, don't know why)
- add script:

` "scripts": {`
 `  "toolbox": "react-toolbox-themr"`
 `}`

- `yarn run toolbox'  (this creates a folder toolbox in my src folder)
- add ThemeProvider in `index.js`

` import React          from 'react';`
` import { render }     from 'react-dom';`
` import MyApp from './app/containers/app';`
` import './toolbox/theme.css';`
` import theme from './toolbox/theme.js'`
` import ThemeProvider from 'react-toolbox/lib/ThemeProvider';**`
 
`const rootElement = document.getElementById('root');`
 `render(`
 `    <ThemeProvider theme={theme}>`
 `        <MyApp/>`
 `    </ThemeProvider>, rootElement );`

**File Structure**
.
..
app
index.js
toolbox

Thanks for any help!

**Comment by javivelasco** [comment]
This is solved with `beta.6` and the latest patch :)

**Comment by akoenig** [comment]
@javivelasco Thanks for your fast response but I'm still facing the problem with `beta.6`.

**Comment by javivelasco** [comment]
Please try removing `node_modules` and make sure you have the latest version for both projects. Composition was removed in `beta.6` so that error doesn't make sense at all now :/

**Comment by vasa-chi** [comment]
Yep, still seing this.
```
Failed to compile.

Error in ./~/react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird
    at Array.map (native)
 @ ./~/react-toolbox/lib/button/theme.css 4:14-120 13:2-17:4 14:20-126
```

package.json
```json
{
  "name": "ttable",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "0.8.5"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-toolbox": "2.0.0-beta.6",
    "react-toolbox-themr": "^1.0.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "toolbox": "react-toolbox-themr",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}
```

**Comment by vasa-chi** [comment]
FWIW, the error happens when I `import AppBar from "react-toolbox/lib/app_bar";`. Importing Buttom, for instance, compiles successfully.
I'm on macOS, so this probably isn't a Windows-only issue.

**Comment by javivelasco** [comment]
This is the same as reported in #15

I have to debug it a bit, I'm looking at it as soon as possible.

**Comment by javivelasco** [comment]
Actually the reason is explained at #17. You have to import components raw!

**Comment by vasa-chi** [comment]
OK, thanks :)

**Comment by bnortman** [comment]
What do you mean by importing components raw?
